In [1]:
import numpy as np
import pandas as pd 
import cx_Oracle as co 
from DbConn import *

In [6]:
db=DbConn()

In [10]:
query_result = pd.read_sql("SELECT GENRENM FROM MOVIEDETAIL  ", db.connection)
query_result

     GENRENM
0        스릴러
1      애니메이션
2         범죄
3      애니메이션
4      애니메이션
5         액션
6        스릴러
7      애니메이션
8        드라마
9        스릴러
10        액션
11     애니메이션
12       드라마
13        액션
14       드라마
15        범죄
16       드라마
17       드라마
18     애니메이션
19     애니메이션
20       스릴러
21    멜로/로맨스
22        액션
23     애니메이션
24     애니메이션
25        SF
26       판타지
27     다큐멘터리
28        기타
29       코미디
...      ...
1524     코미디
1525     드라마
1526     코미디
1527   애니메이션
1528     드라마
1529      가족
1530   애니메이션
1531     드라마
1532      액션
1533    미스터리
1534   애니메이션
1535     드라마
1536      액션
1537     코미디
1538   애니메이션
1539      액션
1540  공포(호러)
1541   애니메이션
1542      사극
1543     드라마
1544      액션
1545   애니메이션
1546      SF
1547      범죄
1548   애니메이션
1549     스릴러
1550     드라마
1551      액션
1552      액션
1553      액션

[1554 rows x 1 columns]

In [26]:
result1 = pd.read_sql('SELECT M.GENRENM, B.SALESACC FROM MOVIEDETAIL M,BOXOFFICE B WHERE M.MOVIECD =B.MOVIECD', db.connection)
result1

      GENRENM      SALESACC
0         판타지   79893706032
1         드라마   22687239737
2          액션     967150400
3       애니메이션     389865000
4          액션   33513333066
5         드라마    7633666300
6       애니메이션    3552985500
7         드라마     910094900
8       애니메이션    6035975700
9       애니메이션    2847029700
10        판타지   81523604632
11        드라마   23928179037
12         액션    1784501500
13      애니메이션     738605800
14         액션   33707043766
15        드라마    7820591800
16      애니메이션   29663633456
17      애니메이션    3591602700
18        드라마     948851000
19      애니메이션    6059760600
20        판타지   83775075875
21        드라마   25636269734
22         액션    2926838580
23      애니메이션    1102318100
24        드라마    8062669700
25         액션   33935611866
26        드라마     998584777
27      애니메이션   29709621156
28      애니메이션    3624679600
29      애니메이션    6083556100
...       ...           ...
21843    어드벤처   48537650400
21844      사극    5724727770
21845     드라마   19338014700
21846   애니메이션  110775480740
21847   애니메이션    4922088000
21848     뮤지컬    5838643210
21849      액션   10349888380
21850   애니메이션     889321900
21851   애니메이션     877404060
21852    미스터리    5443472790
21853    어드벤처   50375689800
21854      사극    6632608330
21855     드라마   20134261100
21856   애니메이션  111156673720
21857   애니메이션    5105955900
21858     뮤지컬    5991392190
21859     코미디     128233000
21860      액션   10456808140
21861   애니메이션     965677900
21862   애니메이션     956243000
21863    어드벤처   52905789770
21864      사극    7808242950
21865     드라마   21236477800
21866      액션    1085659520
21867   애니메이션  111596248720
21868   애니메이션    5299942440
21869      액션   10612013680
21870    미스터리    5648860210
21871   애니메이션    1044574960
21872     뮤지컬    6093167690

[21873 rows x 2 columns]

In [189]:
result1 = pd.read_sql('SELECT COMPANYCD1,M.GENRENM, B.SALESACC,M.NATIONS FROM MOVIEDETAIL M,BOXOFFICE B WHERE M.MOVIECD =B.MOVIECD', db.connection)
#audiAcc
result1.head()

   COMPANYCD1 GENRENM     SALESACC NATIONS
0    20100540     판타지  79893706032      한국
1    20160263     드라마  22687239737      한국
2    20173221      액션    967150400      미국
3    20100041   애니메이션    389865000      미국
4    20158288      액션  33513333066      한국

In [190]:
#pd.Data

In [191]:
#result1.groupby("GENRENM","NATIONS")

In [192]:
result1["NATIONS2"]=pd.Categorical(result1.NATIONS)
result1.head()

   COMPANYCD1 GENRENM     SALESACC NATIONS NATIONS2
0    20100540     판타지  79893706032      한국       한국
1    20160263     드라마  22687239737      한국       한국
2    20173221      액션    967150400      미국       미국
3    20100041   애니메이션    389865000      미국       미국
4    20158288      액션  33513333066      한국       한국

In [193]:
result1["GENREUM2"]=pd.Categorical(result1.GENRENM)
result1

       COMPANYCD1 GENRENM     SALESACC NATIONS NATIONS2 GENREUM2
0        20100540     판타지  79893706032      한국       한국      판타지
1        20160263     드라마  22687239737      한국       한국      드라마
2        20173221      액션    967150400      미국       미국       액션
3        20100041   애니메이션    389865000      미국       미국    애니메이션
4        20158288      액션  33513333066      한국       한국       액션
5        20161801     드라마   7633666300      미국       미국      드라마
6        20142048   애니메이션   3552985500      일본       일본    애니메이션
7        20102327     드라마    910094900      미국       미국      드라마
8        20020113   애니메이션   6035975700      한국       한국    애니메이션
9        20168728   애니메이션   2847029700      독일       독일    애니메이션
10       20100540     판타지  81523604632      한국       한국      판타지
11       20160263     드라마  23928179037      한국       한국      드라마
12       20173221      액션   1784501500      미국       미국       액션
13       20100041   애니메이션    738605800      미국       미국    애니메이션
14       20158288      액션  33707043766      한국       한국       액션
15       20161801     드라마   7820591800      미국       미국      드라마
16       20141469   애니메이션  29663633456      일본       일본    애니메이션
17       20142048   애니메이션   3591602700      일본       일본    애니메이션
18       20102327     드라마    948851000      미국       미국      드라마
19       20020113   애니메이션   6059760600      한국       한국    애니메이션
20       20100540     판타지  83775075875      한국       한국      판타지
21       20160263     드라마  25636269734      한국       한국      드라마
22       20173221      액션   2926838580      미국       미국       액션
23       20100041   애니메이션   1102318100      미국       미국    애니메이션
24       20161801     드라마   8062669700      미국       미국      드라마
25       20158288      액션  33935611866      한국       한국       액션
26       20102327     드라마    998584777      미국       미국      드라마
27       20141469   애니메이션  29709621156      일본       일본    애니메이션
28       20142048   애니메이션   3624679600      일본       일본    애니메이션
29       20020113   애니메이션   6083556100      한국       한국    애니메이션
...           ...     ...          ...     ...      ...      ...
21843    20100340      사극   8878664310      한국       한국       사극
21844    20141352      SF    198626400      미국       미국       SF
21845    20139135  멜로/로맨스    254498777      미국       미국   멜로/로맨스
21846    20100041      액션   1841456500      미국       미국       액션
21847    20103649  멜로/로맨스   3119147800      미국       미국   멜로/로맨스
21848    20104247      액션   5427592563      미국       미국       액션
21849     2013214     드라마  10609563847      한국       한국      드라마
21850    20139135    어드벤처    216782300     스웨덴      스웨덴     어드벤처
21851    20100043      액션  13476863452      미국       미국       액션
21852    20101104     드라마   2021137836      미국       미국      드라마
21853    20100520      범죄    485881252      미국       미국       범죄
21854    20111485      범죄    599094764      한국       한국       범죄
21855    20062097      액션  25041881300      한국       한국       액션
21856    20062097      액션  22950491300      한국       한국       액션
21857    20062083      액션  95900443652      한국       한국       액션
21858    20100603   애니메이션  18809726578      미국       미국    애니메이션
21859    20142048      액션    867525730     프랑스      프랑스       액션
21860     2013216     드라마    363993200      미국       미국      드라마
21861    20100043      액션  38002701701      미국       미국       액션
21862    20110891      범죄  12089900583      한국       한국       범죄
21863    20100834     드라마   2015282936      한국       한국      드라마
21864     2013216   애니메이션   1939160000      독일       독일    애니메이션
21865    20100450    미스터리  42340235592      한국       한국     미스터리
21866    20020113   애니메이션   1779991900      한국       한국    애니메이션
21867    20110854      액션  37325028983      미국       미국       액션
21868    20125035   애니메이션     57651500      일본       일본    애니메이션
21869    20062083      액션  98284072081      한국       한국       액션
21870    20122737      사극   9113226311      한국       한국       사극
21871    20100043      액션  38569973201      미국       미국       액션
21872    20060452   애니메이션  18883845060      미국       미국    애니메이션

[21873 rows x 6 columns]

In [194]:
#result1=result1.groupby("NATIONS","GENRENM2")

In [195]:
result1["NATIONS2"]=result1.NATIONS2.cat.codes 
result1.head()

   COMPANYCD1 GENRENM     SALESACC NATIONS  NATIONS2 GENREUM2
0    20100540     판타지  79893706032      한국        32      판타지
1    20160263     드라마  22687239737      한국        32      드라마
2    20173221      액션    967150400      미국        10       액션
3    20100041   애니메이션    389865000      미국        10    애니메이션
4    20158288      액션  33513333066      한국        32       액션

In [196]:
result1["GENREUM2"]=result1.GENREUM2.cat.codes
result1

       COMPANYCD1 GENRENM     SALESACC NATIONS  NATIONS2  GENREUM2
0        20100540     판타지  79893706032      한국        32        18
1        20160263     드라마  22687239737      한국        32         6
2        20173221      액션    967150400      미국        10        14
3        20100041   애니메이션    389865000      미국        10        13
4        20158288      액션  33513333066      한국        32        14
5        20161801     드라마   7633666300      미국        10         6
6        20142048   애니메이션   3552985500      일본        23        13
7        20102327     드라마    910094900      미국        10         6
8        20020113   애니메이션   6035975700      한국        32        13
9        20168728   애니메이션   2847029700      독일         6        13
10       20100540     판타지  81523604632      한국        32        18
11       20160263     드라마  23928179037      한국        32         6
12       20173221      액션   1784501500      미국        10        14
13       20100041   애니메이션    738605800      미국        10        13
14       20158288      액션  33707043766      한국        32        14
15       20161801     드라마   7820591800      미국        10         6
16       20141469   애니메이션  29663633456      일본        23        13
17       20142048   애니메이션   3591602700      일본        23        13
18       20102327     드라마    948851000      미국        10         6
19       20020113   애니메이션   6059760600      한국        32        13
20       20100540     판타지  83775075875      한국        32        18
21       20160263     드라마  25636269734      한국        32         6
22       20173221      액션   2926838580      미국        10        14
23       20100041   애니메이션   1102318100      미국        10        13
24       20161801     드라마   8062669700      미국        10         6
25       20158288      액션  33935611866      한국        32        14
26       20102327     드라마    998584777      미국        10         6
27       20141469   애니메이션  29709621156      일본        23        13
28       20142048   애니메이션   3624679600      일본        23        13
29       20020113   애니메이션   6083556100      한국        32        13
...           ...     ...          ...     ...       ...       ...
21843    20100340      사극   8878664310      한국        32        11
21844    20141352      SF    198626400      미국        10         0
21845    20139135  멜로/로맨스    254498777      미국        10         7
21846    20100041      액션   1841456500      미국        10        14
21847    20103649  멜로/로맨스   3119147800      미국        10         7
21848    20104247      액션   5427592563      미국        10        14
21849     2013214     드라마  10609563847      한국        32         6
21850    20139135    어드벤처    216782300     스웨덴        13        15
21851    20100043      액션  13476863452      미국        10        14
21852    20101104     드라마   2021137836      미국        10         6
21853    20100520      범죄    485881252      미국        10        10
21854    20111485      범죄    599094764      한국        32        10
21855    20062097      액션  25041881300      한국        32        14
21856    20062097      액션  22950491300      한국        32        14
21857    20062083      액션  95900443652      한국        32        14
21858    20100603   애니메이션  18809726578      미국        10        13
21859    20142048      액션    867525730     프랑스        30        14
21860     2013216     드라마    363993200      미국        10         6
21861    20100043      액션  38002701701      미국        10        14
21862    20110891      범죄  12089900583      한국        32        10
21863    20100834     드라마   2015282936      한국        32         6
21864     2013216   애니메이션   1939160000      독일         6        13
21865    20100450    미스터리  42340235592      한국        32         9
21866    20020113   애니메이션   1779991900      한국        32        13
21867    20110854      액션  37325028983      미국        10        14
21868    20125035   애니메이션     57651500      일본        23        13
21869    20062083      액션  98284072081      한국        32        14
21870    20122737      사극   9113226311      한국        32        11
21871    20100043      액션  38569973201      미국        10        14
21872    20060452   애니메이션  18883845060      미국        10        13

[21873 rows x 6 columns]

In [197]:
# result1.drop("NATIONS3",axis=1)
# result1
# iris["species2"]=pd.Categorical(iris.species) #카테고리컬한 데이터로 만듦 
# #iris의 species2를 판다스 모듈로 iris의 species를 카테고리컬한 데이터로 만듦 
# iris.head() #카테

In [198]:
result1[['SALESACC','NATIONS2']].corr()

          SALESACC  NATIONS2
SALESACC   1.00000   0.08593
NATIONS2   0.08593   1.00000

In [199]:
result1.corr()#salesacc 매출액 nation 국가 genreum2 장르

            COMPANYCD1  SALESACC  NATIONS2  GENREUM2
COMPANYCD1    1.000000  0.046203 -0.038958  0.008755
SALESACC      0.046203  1.000000  0.085930  0.125867
NATIONS2     -0.038958  0.085930  1.000000 -0.110548
GENREUM2      0.008755  0.125867 -0.110548  1.000000